lines:
  bounding_box:
    top: 349
    left: 4415
    width: 112
    height: 29
score:
  bounding_box:
    top: 168
    left: 4383
    width: 173
    height: 28
playfield:
  bounding_box:
    top: 88
    left: 4070
    width: 312
    height: 468


