capturer: screen
highscores:
  level9: 556084
  level9hearth: 125840
  levelk: 97020
interceptor:
  camera:
    api: 700
    index: 0
mode: score
obs:
  bounding_box:
    height: 468
    left: 75
    top: 126
    width: 519
  camera:
    api: 700
    index: 2
plotter: piece_distribution
rom_version: orig
screen:
  bounding_box:
    height: 471
    left: 392
    top: 630
    width: 524
